# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: baza_migrations 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "baza_migrations".freeze
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["kaspernj".freeze]
  s.date = "2017-01-27"
  s.description = "Migrations support for the Baza database framework in Ruby.".freeze
  s.email = "k@spernj.org".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop_todo.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "baza_migrations.gemspec",
    "config/best_project_practice_rubocop.yml",
    "config/best_project_practice_rubocop_todo.yml",
    "lib/baza_migrations.rb",
    "lib/baza_migrations/commands.rb",
    "lib/baza_migrations/commands/add_column.rb",
    "lib/baza_migrations/commands/add_index.rb",
    "lib/baza_migrations/commands/base.rb",
    "lib/baza_migrations/commands/create_table.rb",
    "lib/baza_migrations/commands/drop_table.rb",
    "lib/baza_migrations/commands/remove_column.rb",
    "lib/baza_migrations/commands/remove_index.rb",
    "lib/baza_migrations/errors.rb",
    "lib/baza_migrations/migrate.rb",
    "lib/baza_migrations/migration.rb",
    "lib/baza_migrations/migrations_executor.rb",
    "lib/tasks/baza.rake",
    "shippable.yml",
    "spec/dummy/db/baza_migrate/20150901160500_create_users.rb",
    "spec/dummy/db/baza_migrate/20150901161800_create_user_roles.rb",
    "spec/lib/baza_migrations/migration_spec.rb",
    "spec/lib/baza_migrations/migrations_executor_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_classes/201503041644_test_change_migration.rb",
    "spec/test_classes/201503041646_test_up_down_migration.rb",
    "spec/test_classes/201509101727_test_exists_methods.rb"
  ]
  s.homepage = "http://github.com/kaspernj/baza_migrations".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Migrations support for the Baza database framework in Ruby.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<baza>.freeze, ["~> 0.0.20"])
      s.add_runtime_dependency(%q<string-cases>.freeze, ["~> 0.0.1"])
      s.add_runtime_dependency(%q<auto_autoloader>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, ["= 3.5.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
      s.add_development_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
      s.add_development_dependency(%q<sqlite3>.freeze, [">= 0"])
      s.add_development_dependency(%q<wref>.freeze, ["= 0.0.8"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
    else
      s.add_dependency(%q<baza>.freeze, ["~> 0.0.20"])
      s.add_dependency(%q<string-cases>.freeze, ["~> 0.0.1"])
      s.add_dependency(%q<auto_autoloader>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, ["= 3.5.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
      s.add_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
      s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
      s.add_dependency(%q<wref>.freeze, ["= 0.0.8"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
    end
  else
    s.add_dependency(%q<baza>.freeze, ["~> 0.0.20"])
    s.add_dependency(%q<string-cases>.freeze, ["~> 0.0.1"])
    s.add_dependency(%q<auto_autoloader>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["= 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["= 2.3.3"])
    s.add_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
    s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
    s.add_dependency(%q<wref>.freeze, ["= 0.0.8"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.10"])
  end
end

